Repository garudatechnologydevelopers/Sketch-icons, pull requests merged in 2022-10, with the labels that each got.

#48 updated readme
  readme.md
Labels: hacktoberfest

#51 added alignment icons
  icon_list.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#52 upto badge-8k
  icon_list.md
Labels: hacktoberfest, hacktoberfest-accepted

#53 Created new Contributors graph
  readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#54 Removed Content
  readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#55 upto caps-lock-1 icons readme
  icon_list.md
Labels: hacktoberfest-accepted
